import {
  moderateScale,
  moderateVerticalScale,
  scale,
  ScaledSheet,
} from 'react-native-size-matters';
import {Colors, fullWidth, shadow, spacing} from '../../theme';

export const styles = ScaledSheet.create({
  wrapHeader: {
    height: moderateScale(38),
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    left: moderateScale(12),
  },
  wrapMenu: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
    borderRadius: 333,
    backgroundColor: '#00000040',
  },
  icMenu: {
    width: moderateScale(24),
    height: moderateScale(24),
  },
  appName: {
    color: '#fff',
    fontSize: moderateScale(20),
    fontWeight: '600',
  },
  wrapTime: {
    height: 52,
    width: '100%',
    paddingHorizontal: spacing.large,
    marginTop: 12,
  },
  icProfile: {
    width: 44,
    height: 44,
    borderRadius: 333,
    resizeMode: 'cover',
  },
  wrapItem: {
    width: (fullWidth - 61) * 0.5,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },

  wrapTimeDown: {
    flex: 1,
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
  },
  viewWrapTime: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: spacing.large,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeCountDown: {
    color: '#723000',
    fontSize: moderateScale(18),
    fontWeight: '700',
    textAlign: 'center',
  },
  wraplotte: {
    width: 36,
    height: 36,
  },

  wrapContent: {
    flex: 1,

    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
    // alignItems: 'center',
    backgroundColor: '#fbfbfb',
   
  },
  wrapPsRate: {
    marginTop: spacing.large,
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: moderateScale(56),
    borderRadius: moderateScale(16),
    width: fullWidth - 48,
    backgroundColor: '#D8FBFF',
    paddingHorizontal: spacing.large,
    alignItems: 'center',
  },
  txtPassRate: {
    color: '#242424',
    fontWeight: '500',
    fontSize: moderateScale(16),
    marginLeft: 16,
  },
  rate: {
    fontWeight: '700',
    fontSize: moderateScale(20),
    color: '#34C759',
  },
  wrapItemContent: {
    flexDirection: 'column',
    width: fullWidth - 48,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    gap: 12,
    borderRadius: '16@ms',
    paddingHorizontal: scale(12),
    paddingVertical: 16,
    marginTop: moderateScale(22),
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.2,
    shadowRadius: 2.0,
    elevation: 5,
  },
  viewCircularProgress: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#EFEFF6',
    borderRadius: 16,
    height: '104@ms',
    width: '100%',
    paddingVertical: 12,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewBoxLine: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderColor: '#EFEFF6',
    height: '40@ms',
    width: '100%',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(60),
  },
  lineBorder: {
    width: 1,
    height: '80@ms',
    backgroundColor: '#EFEFF6',
  },
  txtAVGPass: {
    fontSize: moderateScale(12),
    paddingTop: 5,
    color: Colors.black_text,
    fontWeight: '500',
    textAlign: 'center',
  },
  stylesTimeQuestion: {
    color: '#0B9FF1',
    fontSize: moderateScale(16),
    fontWeight: '600',
  },
  btnDetail: {
    borderRadius: 333,
    borderWidth: 1,
    borderColor: '#0F90EB',
    width: '49%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: moderateVerticalScale(14),
  },
  txtDetail: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#0B9FF1',
  },
  titleTopicDays: {
    color: Colors.black_text,
    fontSize: moderateScale(16),
    fontWeight: '600',
  },
  with100: {
    width: '100%',
  },
  dropdown: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '28@ms',
  },
  btnBack: {
    width: '40@s',
  },
  viewHeader: {
    width: '40@s',
    height: '40@ms',
    padding: 8,
  },

  valueRedo: {
    color: '#FFAD33',
    fontSize: moderateScale(16),
    fontWeight: '600',
    paddingRight: 5,
  },
  valueRefresh: {
    color: '#0B9FF1',
    fontSize: moderateScale(16),
    fontWeight: '600',
    paddingRight: 5,
  },
  viewContentValue: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: '24@ms',
  },
  viewSelectItem: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewTextHeader: {
    width: '100%',
    paddingRight: moderateScale(100),
  },
});
